repos:
- repo: https://github.com/gitleaks/gitleaks
  rev: v8.24.2
  hooks:
  - id: gitleaks-system
    name: Detect hardcoded secrets using Gitleaks
    description: Detect hardcoded secrets using Gitleaks
    entry: gitleaks git --pre-commit --redact --staged --verbose
    language: system
    pass_filenames: false