name: Frackend

on:
  push:
    branches:
      - 'main'
      - 'dev/*'
    paths:
      - '.github/workflows/team-frackend.yml'
      - 'apps/frackend/**'
      - 'apps/frontend/**'
      - 'apps/frontend-2/**'
env:
  IMAGE: ghcr.io/${{ github.repository }}/teamfrackend:${{ github.sha }}

jobs:
  build:
    name: Build and push docker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.2
      - uses: actions/setup-node@v3.5.1
        with:
          node-version: 16
          cache: 'npm'
          cache-dependency-path: apps/frackend/package-lock.json
      - name: Install dependencies
        working-directory: apps/frackend
        run: |
          npm ci

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        working-directory: apps/frontend
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v3
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: install
        working-directory: apps/frontend
        run: yarn install

      - name: use prod config
        working-directory: apps/frontend
        if: github.ref == 'refs/heads/main'
        run: cp .env.prod .env

      - name: add version
        env:
          GITHUB_SHA: ${{ github.sha }}
        working-directory: apps/frackend
        run: echo "REACT_APP_GIT_VERSION=${GITHUB_SHA}" >> .env

      - name: Build
        run: CI=false yarn run build
        working-directory: apps/frontend

      - name: copy build
        working-directory: apps/frontend
        run: cp -r build/ ../frackend/public

# beta workflow -- START

      - name: Get yarn cache directory path beta
        id: yarn-cache-beta-dir-path
        working-directory: apps/frontend-2
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v3
        id: yarn-cache-beta
        with:
          path: ${{ steps.yarn-cache-beta-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: install beta
        working-directory: apps/frontend-2
        run: yarn install

      - name: use prod config for beta
        working-directory: apps/frontend-2
        if: github.ref == 'refs/heads/main'
        run: cp .env.prod .env

      - name: add version to beta
        env:
          GITHUB_SHA: ${{ github.sha }}
        working-directory: apps/frontend-2
        run: echo "VITE_APP_GIT_VERSION=${GITHUB_SHA}" >> .env

      - name: Build beta
        run: CI=false yarn run build
        working-directory: apps/frontend-2

      - name: copy beta build
        working-directory: apps/frontend-2
        run: cp -r dist/ ../frackend/public2
        
# beta workflow -- END

      - name: Docker login
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker container
        uses: docker/build-push-action@v3
        with:
          context: apps/frackend
          push: true
          tags: ${{ env.IMAGE }}


  deploy-dev:
    name: Deploy dev-gcp
    needs: build
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/dev')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.2
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_ORG_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: apps/frackend/nais/frackend.yaml
          VARS: apps/frackend/nais/frackend-dev-gcp-vars.yaml

  deploy-prod:
    name: Deploy prod-gcp
    needs: deploy-dev
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.2
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_ORG_DEPLOY_APIKEY }}
          CLUSTER: prod-gcp
          RESOURCE: apps/frackend/nais/frackend.yaml
          VARS: apps/frackend/nais/frackend-prod-gcp-vars.yaml
