name: Ingress-redirect

on:
  push:
    branches:
      - 'main'
      - 'dev/*'
    paths:
      - '.github/workflows/team-ingress-redirect.yml'
      - 'apps/ingress-redirect/**'

env:
  IMAGE: docker.pkg.github.com/${{ github.repository }}/teamfront${{ github.ref == 'refs/heads/main' }}:${{ github.sha }}

defaults:
  run:
    working-directory: apps/ingress-redirect

jobs:
  build:
    name: Ingress-redirect - build and push docker
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.3.0
      - name: Set up node
        uses: actions/setup-node@v2.2.0
        with:
          node-version: '16.x'
      - name: Docker
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          docker build --tag ${IMAGE} .
          docker login docker.pkg.github.com -u ${GITHUB_REPOSITORY} -p ${GITHUB_TOKEN}
          docker push ${IMAGE}

  deploy-preprod:
    name: Ingress-redirect - deploy Dev FSS
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.0
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-fss
          RESOURCE: apps/ingress-redirect/nais/frontend-fss.yaml
          VARS: apps/ingress-redirect/nais/frontend-dev-fss-vars.yaml
          ENVIRONMENT: dev-fss:teamdatajegerne:team-catalog-frontend

  deploy-prod:
    name: Ingress-redirect - deploy Prod FSS
    needs: build
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.0
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-fss
          RESOURCE: apps/ingress-redirect/nais/frontend-fss.yaml
          VARS: apps/ingress-redirect/nais/frontend-prod-fss-vars.yaml
          ENVIRONMENT: prod-fss:teamdatajegerne:team-catalog-frontend

  deploy-prod-sandbox:
    name: ingress-redirect - deploy Sandbox Prod FSS
    needs: build
    if: github.ref == 'refs/heads/sandbox'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.0
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-fss
          RESOURCE: apps/ingress-redirect/nais/frontend-fss.yaml
          VARS: apps/ingress-redirect/nais/frontend-prod-fss-sandbox-vars.yaml
          ENVIRONMENT: prod-fss:teamdatajegerne:team-catalog-sandbox-frontend
